### ISSUE TITLE
error

### ISSUE THREAD

**Issue by delf0b** [DialupHandshake/Cr10V3_klipper_skre3v3#1]
@DialupHandshake  get  Move out of range: 70.126 -34.591 0.300 [-0.750] failure. could you please help me out?  im guessing it has something to do with the CURA(Slicer) Start code.... but im not sure. everything worked fine at first

**Comment by DialupHandshake** [comment]
Does that happen at the end of the print? Could be the PRINT_END macro. Sorry, I'm away for a few days, so I can't check my slicer.

**Comment by delf0b** [comment]
No its when I start a print, I found on the internet it has something to do wit the start Gcode of the slicer. Which slicer are You using? Can I have your start gcode of your slicer when you’re back?

Br,

Bas

**Comment by DialupHandshake** [comment]
It's probably something to do with G90 and G91 when purging. I use Orca Slicer, will put up start gcode as soon as as I get to the computer. Should be sometime tomorrow. What do you currently have in start gcode in Cura?

**Comment by delf0b** [comment]
Thank you so much! 

I will try Orca slicer as well 

I now adjusted my Gcode to this:

G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S[first_layer_temperature] ; set extruder temp
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S[first_layer_bed_temperature] ; wait for bed temp
M109 S[first_layer_temperature] ; wait for extruder temp
G28 ; home all
G1 Z2 F240
G1 X2 Y10 F3000
G1 Z0.28 F240
G92 E0.0
G1 Y190 E15.0 F1500.0 ; intro line
G1 X2.3 F5000
G1 Y10 E30 F1200.0 ; intro line
G92 E0.0


This will give me 1 time a pause that I have to manually need to resume but printer is finally working. I will swap to Orca slicer (already use this for my bambuulab)

**Comment by DialupHandshake** [comment]
That's great! I had a look at my slicer gcode, and it looks like I have changed it since installing KAMP. 
Try setting your start gcoded in slicer to this:
`PRINT_START EXTRUDER_TEMP=[first_layer_temperature] BED_TEMP=[first_layer_bed_temperature]`, and I have updated the printer.cfg in the repository to work with that gcode.
I'm afraid I can't test it, because it won't play nicely with KAMP. Let me know if it gives you any trouble.
I will upload my config with KAMP, should you choose to install it.  KAMP is awesome and I highly recommend it.

**Comment by delf0b** [comment]
Hi, 

Got some days off… so I will and try to setup KAMP. I see the ORCA slicer is almost the same as the one for my Bambulab :) 

I would love to have your slicer startcode..

Br

Bas

**Comment by DialupHandshake** [comment]
Sure, with KAMP my start gcode is just `PRINT_START EXTRUDER_TEMP=[first_layer_temperature] BED_TEMP=[first_layer_bed_temperature]` and everything else is in printer.cfg in KAMP_config folder in this repository. So the slicer gcode just invokes the PRINT_START macro in printer.cfg, tells it what temperatures to use for bed and nozzle, and Klipper does the priming. My end gcode is `PRINT_END
M104 S0
M140 S0` if you need it

**Comment by delf0b** [comment]
￼

I tried the KAMP but can;’t get it to work so ended up copying your files… but even then unfortunately its not working get the following messages and then it starts to do a complete bed mesh…

Got any ideas how to solve this?

**Comment by DialupHandshake** [comment]
I'm afraid I can't see the attachment, what messages are you getting?

**Comment by delf0b** [comment]
When I start a print I get the following message ..

11:33
Unknown command:"M205"
11:33
Unknown command:"M203"
11:33
Unknown command:”M201"





Then after heating the bed 


11:38 Unknown command:”SETUP_LINE_PURGE”
11:39 led_enable : 0
11:39 status_macro: ‘status_meshing'
11:39 fuzz_enable : 1
11:39 fuzz_min : 0.000000
11:39 fuzz_max : 4.000000
11:39 probe_dock_enable: 0
11:39 attach_macro: ‘Attach_Probe'
11:39 detach_macro: ‘Dock_Probe'
11:39 0 object points, clamping to bed mesh [(45.0, 10.0) (290.0, 290.0)]
11:39 Object bounds, clamped to the bed_mesh: (47.99, 13.8), (289.64, 288.94)
11:39 Algorithm: bicubic
11:39 Points: x: 9, y: 9
11:39 Generating new points…

And then starts the full print bed mesh (measurement)

**Comment by DialupHandshake** [comment]
In Orca Slicer printer settings, set your G-code flavor to Klipper. Hopefully that would get rid of those first three "Unknown command" messages. For the rest, it looks like you may have installed the version on KAMP for dockable probe, whereas my config is for a fixed probe. What kind of bed leveling probe, if any, do you use? Also, could you please make sure you have [include KAMP/*cfg] in your printer.cfg? That could be why SETUP_LINE_PURGE is not found. If you want to attach a backup of your config here, I'll be happy to take a look at it.

**Comment by delf0b** [comment]
Ah it’s working :). I did include KAMP/cfg instead of KAMP/*cfg.

Thank you so much for your help

**Comment by DialupHandshake** [comment]
Nice one that's great! I'll close the issue but feel free to open another if you need more help.
